// ENHANCED: /api/dna-quality-assessment/route.js
// Real-time DNA quality assessment before analysis

import sql from "@/app/api/utils/sql";

export async function POST(request) {
  try {
    const { fileUrl, fileName, fileType, species } = await request.json();

    if (!fileUrl) {
      return Response.json(
        { error: "Missing fileUrl" },
        { status: 400 }
      );
    }

    // Download and analyze file
    let fileContent = "";
    let fileSize = 0;
    
    try {
      const fileResponse = await fetch(fileUrl);
      if (!fileResponse.ok) {
        throw new Error("Failed to download file");
      }
      
      const buffer = await fileResponse.arrayBuffer();
      fileSize = buffer.byteLength;
      fileContent = new TextDecoder().decode(buffer);
    } catch (err) {
      return Response.json({
        quality_score: 0,
        grade: "F",
        error: "Could not access file",
        recommendations: ["Check file URL and permissions"]
      });
    }

    // Run comprehensive quality assessment
    const assessment = assessDNAQuality(fileContent, fileName, fileType, species);
    
    return Response.json(assessment);
  } catch (error) {
    console.error("Quality Assessment Error:", error);
    return Response.json(
      { error: "Assessment failed", details: error.message },
      { status: 500 }
    );
  }
}

function assessDNAQuality(content, fileName, fileType, species) {
  const lines = content.split('\n').filter(l => l.trim());
  const totalLines = lines.length;
  
  // Detect format
  const format = detectFormat(content, fileName);
  
  // Calculate metrics
  const metrics = calculateMetrics(content, format);
  
  // Calculate quality score
  const qualityScore = calculateQualityScore(metrics, format);
  
  // Generate grade
  const grade = scoreToGrade(qualityScore);
  
  // Generate recommendations
  const recommendations = generateRecommendations(metrics, qualityScore, format);
  
  // Determine analysis capabilities
  const capabilities = determineCapabilities(qualityScore, metrics);
  
  return {
    quality_score: qualityScore,
    grade: grade,
    format: format,
    metrics: metrics,
    recommendations: recommendations,
    capabilities: capabilities,
    assessed_at: new Date().toISOString()
  };
}

function detectFormat(content, fileName) {
  const lowerContent = content.toLowerCase();
  const lowerName = (fileName || "").toLowerCase();
  
  // VCF detection
  if (lowerName.endsWith('.vcf') || 
      content.includes('##fileformat=VCF') ||
      content.includes('#CHROM\tPOS\tID\tREF\tALT')) {
    return { type: "VCF", confidence: 0.99 };
  }
  
  // 23andMe detection
  if (content.includes('rsid\tchromosome\tposition\tgenotype') ||
      content.includes('# This data file generated by 23andMe')) {
    return { type: "23andMe", confidence: 0.99 };
  }
  
  // AncestryDNA detection
  if (content.includes('rsid\tchromosome\tposition\tallele1\tallele2') ||
      content.includes('# AncestryDNA')) {
    return { type: "AncestryDNA", confidence: 0.99 };
  }
  
  // Embark detection
  if (lowerName.includes('embark') ||
      content.includes('Embark') ||
      content.includes('marker,chromosome,position,genotype')) {
    return { type: "Embark", confidence: 0.95 };
  }
  
  // Wisdom Panel detection
  if (lowerName.includes('wisdom') ||
      content.includes('Wisdom Panel') ||
      content.includes('AFFX-SP-')) {
    return { type: "WisdomPanel", confidence: 0.95 };
  }
  
  // Basepaws detection
  if (lowerName.includes('basepaws') ||
      content.includes('Basepaws') ||
      content.includes('CatDNA')) {
    return { type: "Basepaws", confidence: 0.95 };
  }
  
  // FASTA detection
  if (lowerName.endsWith('.fasta') || lowerName.endsWith('.fa')) {
    return { type: "FASTA", confidence: 0.99 };
  }
  
  // Generic CSV/TXT
  if (lowerName.endsWith('.csv')) {
    return { type: "GenericCSV", confidence: 0.70 };
  }
  
  if (lowerName.endsWith('.txt')) {
    return { type: "GenericTXT", confidence: 0.60 };
  }
  
  return { type: "Unknown", confidence: 0.30 };
}

function calculateMetrics(content, format) {
  const lines = content.split('\n').filter(l => l.trim());
  const totalSize = content.length;
  
  // Skip header lines
  const dataLines = lines.filter(l => !l.startsWith('#') && !l.startsWith('>'));
  
  // Count variants/SNPs
  let variantCount = 0;
  let uniqueChromosomes = new Set();
  let rsidCount = 0;
  let genotypeCount = 0;
  
  for (const line of dataLines.slice(0, 10000)) {
    const parts = line.split(/[\t,]/);
    
    // Count rsIDs
    if (line.includes('rs')) rsidCount++;
    
    // Count genotypes (looking for patterns like AA, AT, 0/1, etc)
    if (parts.some(p => /^[ACGT]{1,2}$/.test(p) || /^[01][\/|][01]$/.test(p))) {
      genotypeCount++;
    }
    
    // Extract chromosomes
    const chrom = parts[1] || parts[0];
    if (chrom && /^[1-9XYM]$|^chr/i.test(chrom)) {
      uniqueChromosomes.add(chrom.replace(/^chr/i, '').toUpperCase());
    }
    
    variantCount++;
  }
  
  // Calculate SNP density (variants per 1000 lines)
  const snpDensity = variantCount > 0 ? (rsidCount / variantCount) : 0;
  
  // Estimate coverage based on variant count
  let coverage = "unknown";
  if (variantCount > 500000) coverage = "comprehensive";
  else if (variantCount > 100000) coverage = "high";
  else if (variantCount > 20000) coverage = "good";
  else if (variantCount > 5000) coverage = "moderate";
  else coverage = "low";
  
  // Calculate missing data percentage
  const emptyLines = lines.filter(l => l.trim() === '').length;
  const missingDataPct = lines.length > 0 ? (emptyLines / lines.length) : 0;
  
  return {
    total_variants: variantCount,
    rsid_count: rsidCount,
    genotype_count: genotypeCount,
    chromosomes_detected: Array.from(uniqueChromosomes),
    chromosome_count: uniqueChromosomes.size,
    snp_density: Math.round(snpDensity * 1000) / 1000,
    coverage: coverage,
    missing_data_percentage: Math.round(missingDataPct * 100 * 100) / 100,
    file_size_kb: Math.round(content.length / 1024),
    data_lines: dataLines.length
  };
}

function calculateQualityScore(metrics, format) {
  let score = 0;
  
  // Format detection (10 points)
  score += format.confidence * 10;
  
  // Variant count (30 points)
  if (metrics.total_variants > 500000) score += 30;
  else if (metrics.total_variants > 200000) score += 25;
  else if (metrics.total_variants > 100000) score += 20;
  else if (metrics.total_variants > 50000) score += 15;
  else if (metrics.total_variants > 20000) score += 10;
  else if (metrics.total_variants > 5000) score += 5;
  else score += Math.min(5, metrics.total_variants / 1000);
  
  // Chromosome coverage (20 points)
  const chromCount = metrics.chromosome_count;
  if (chromCount >= 20) score += 20;
  else if (chromCount >= 15) score += 15;
  else if (chromCount >= 10) score += 10;
  else if (chromCount >= 5) score += 5;
  else score += Math.min(5, chromCount);
  
  // SNP density (20 points)
  if (metrics.snp_density > 0.5) score += 20;
  else if (metrics.snp_density > 0.3) score += 15;
  else if (metrics.snp_density > 0.1) score += 10;
  else score += Math.max(0, metrics.snp_density * 100);
  
  // Missing data penalty (subtract up to 20)
  score -= Math.min(20, metrics.missing_data_percentage * 0.2);
  
  // rsID presence bonus (10 points)
  if (metrics.rsid_count > 10000) score += 10;
  else if (metrics.rsid_count > 5000) score += 7;
  else if (metrics.rsid_count > 1000) score += 5;
  else score += Math.min(5, metrics.rsid_count / 200);
  
  // Genotype presence (10 points)
  if (metrics.genotype_count > metrics.total_variants * 0.8) score += 10;
  else if (metrics.genotype_count > metrics.total_variants * 0.5) score += 5;
  
  return Math.round(Math.max(0, Math.min(100, score)) * 100) / 100;
}

function scoreToGrade(score) {
  if (score >= 95) return "A+";
  if (score >= 90) return "A";
  if (score >= 85) return "A-";
  if (score >= 80) return "B+";
  if (score >= 75) return "B";
  if (score >= 70) return "B-";
  if (score >= 65) return "C+";
  if (score >= 60) return "C";
  if (score >= 55) return "C-";
  if (score >= 50) return "D+";
  if (score >= 45) return "D";
  if (score >= 40) return "D-";
  return "F";
}

function generateRecommendations(metrics, score, format) {
  const recs = [];
  
  if (score >= 90) {
    recs.push("Excellent sample quality - suitable for all analysis types");
    recs.push("Comprehensive breed identification possible");
    recs.push("High-confidence health risk predictions");
  } else if (score >= 75) {
    recs.push("Good sample quality - suitable for breed and health analysis");
    if (metrics.total_variants < 100000) {
      recs.push("Consider upgrading to higher-coverage test for rare variant detection");
    }
  } else if (score >= 60) {
    recs.push("Moderate sample quality - suitable for breed identification");
    recs.push("Health predictions may have reduced confidence");
    recs.push("Consider re-sampling for pharmacogenomic analysis");
  } else if (score >= 40) {
    recs.push("Low sample quality - basic breed analysis only");
    recs.push("Health predictions not recommended");
    recs.push("Strongly recommend re-sampling with proper technique");
  } else {
    recs.push("Sample quality too low for reliable analysis");
    recs.push("Analysis not recommended with current sample");
    recs.push("Please re-sample following proper collection guidelines");
  }
  
  // Format-specific recommendations
  if (format.type === "Unknown") {
    recs.push("File format not recognized - may need conversion");
  }
  
  if (metrics.missing_data_percentage > 10) {
    recs.push("High missing data detected - may indicate sample degradation");
  }
  
  if (metrics.chromosome_count < 10) {
    recs.push("Limited chromosome coverage - some analyses may be incomplete");
  }
  
  return recs;
}

function determineCapabilities(score, metrics) {
  return {
    breed_identification: score >= 50,
    health_predispositions: score >= 70,
    pharmacogenomics: score >= 80,
    rare_variant_detection: score >= 90,
    ancestry_analysis: score >= 60,
    behavioral_genetics: score >= 65,
    breeding_compatibility: score >= 75,
    trait_prediction: score >= 55
  };
}
