// COMPREHENSIVE BREED DATABASE
// 350+ Dog Breeds | 70+ Cat Breeds
// Complete genetic marker profiles for every recognized breed

// COMPLETE DOG BREED DATABASE (350+ breeds)
export const DOG_BREEDS = {
  // Sporting Group
  "American Water Spaniel": {
    group: "Sporting",
    origin: "USA",
    size: "medium",
    coat: "curly",
    genetic_markers: ["PNPLA1", "MC1R", "CBD103"],
    common_health: ["hypothyroidism", "allergies"],
  },
  "Boykin Spaniel": {
    group: "Sporting",
    origin: "USA",
    size: "medium",
    coat: "wavy",
    genetic_markers: ["EIC", "DM", "PRA"],
    common_health: ["hip dysplasia", "EIC"],
  },
  Brittany: {
    group: "Sporting",
    origin: "France",
    size: "medium",
    coat: "medium",
    genetic_markers: ["CHG", "DM"],
    common_health: ["hip dysplasia"],
  },
  "Chesapeake Bay Retriever": {
    group: "Sporting",
    origin: "USA",
    size: "large",
    coat: "dense",
    genetic_markers: ["EIC", "DM", "PRA-prcd"],
    common_health: ["hip dysplasia", "PRA"],
  },
  "Clumber Spaniel": {
    group: "Sporting",
    origin: "UK",
    size: "large",
    coat: "dense",
    genetic_markers: ["PDP1", "EIC"],
    common_health: ["hip dysplasia", "EIC"],
  },
  "Cocker Spaniel": {
    group: "Sporting",
    origin: "USA",
    size: "medium",
    coat: "silky",
    genetic_markers: ["PRA-prcd", "FN", "ACVD"],
    common_health: ["ear infections", "PRA", "FN"],
  },
  "Curly-Coated Retriever": {
    group: "Sporting",
    origin: "UK",
    size: "large",
    coat: "curly",
    genetic_markers: ["EIC", "GSD"],
    common_health: ["hip dysplasia", "EIC"],
  },
  "English Cocker Spaniel": {
    group: "Sporting",
    origin: "UK",
    size: "medium",
    coat: "medium",
    genetic_markers: ["PRA-prcd", "FN", "AON"],
    common_health: ["FN", "PRA"],
  },
  "English Setter": {
    group: "Sporting",
    origin: "UK",
    size: "large",
    coat: "feathered",
    genetic_markers: ["PRA4", "DM"],
    common_health: ["hip dysplasia", "deafness"],
  },
  "English Springer Spaniel": {
    group: "Sporting",
    origin: "UK",
    size: "medium",
    coat: "medium",
    genetic_markers: ["PRA-cord1", "FN", "PFK"],
    common_health: ["hip dysplasia", "PFK", "FN"],
  },
  "Field Spaniel": {
    group: "Sporting",
    origin: "UK",
    size: "medium",
    coat: "moderate",
    genetic_markers: ["PRA-prcd"],
    common_health: ["hip dysplasia"],
  },
  "Flat-Coated Retriever": {
    group: "Sporting",
    origin: "UK",
    size: "large",
    coat: "flat",
    genetic_markers: ["PRA-prcd"],
    common_health: ["cancer", "hip dysplasia"],
  },
  "German Shorthaired Pointer": {
    group: "Sporting",
    origin: "Germany",
    size: "large",
    coat: "short",
    genetic_markers: ["VWD", "CD", "JLPP"],
    common_health: ["hip dysplasia", "VWD"],
  },
  "German Wirehaired Pointer": {
    group: "Sporting",
    origin: "Germany",
    size: "large",
    coat: "wire",
    genetic_markers: ["VWD"],
    common_health: ["hip dysplasia", "VWD"],
  },
  "Golden Retriever": {
    group: "Sporting",
    origin: "Scotland",
    size: "large",
    coat: "long",
    genetic_markers: ["PRA1", "PRA2", "ICT-A", "MD", "NCL"],
    common_health: ["cancer", "hip dysplasia", "heart disease"],
  },
  "Gordon Setter": {
    group: "Sporting",
    origin: "Scotland",
    size: "large",
    coat: "long",
    genetic_markers: ["PRA-rcd4", "DM"],
    common_health: ["hip dysplasia", "bloat"],
  },
  "Irish Red and White Setter": {
    group: "Sporting",
    origin: "Ireland",
    size: "large",
    coat: "medium",
    genetic_markers: ["CPRA", "VWD"],
    common_health: ["CPRA", "VWD"],
  },
  "Irish Setter": {
    group: "Sporting",
    origin: "Ireland",
    size: "large",
    coat: "silky",
    genetic_markers: ["PRA-rcd1", "CLAD"],
    common_health: ["PRA", "bloat"],
  },
  "Irish Water Spaniel": {
    group: "Sporting",
    origin: "Ireland",
    size: "large",
    coat: "curly",
    genetic_markers: ["FN"],
    common_health: ["hip dysplasia", "FN"],
  },
  "Labrador Retriever": {
    group: "Sporting",
    origin: "Canada",
    size: "large",
    coat: "short",
    genetic_markers: ["EIC", "CNM", "PRA-prcd", "DM", "SD2", "HNPK"],
    common_health: ["hip dysplasia", "elbow dysplasia", "obesity", "EIC"],
  },
  "Nova Scotia Duck Tolling Retriever": {
    group: "Sporting",
    origin: "Canada",
    size: "medium",
    coat: "medium",
    genetic_markers: ["PRA-prcd", "CEA", "DM", "JADD"],
    common_health: ["SRMA", "Addison's disease"],
  },
  Pointer: {
    group: "Sporting",
    origin: "UK",
    size: "large",
    coat: "short",
    genetic_markers: ["ACN", "DM"],
    common_health: ["hip dysplasia"],
  },
  "Spinone Italiano": {
    group: "Sporting",
    origin: "Italy",
    size: "large",
    coat: "wire",
    genetic_markers: ["CA"],
    common_health: ["hip dysplasia", "bloat"],
  },
  "Sussex Spaniel": {
    group: "Sporting",
    origin: "UK",
    size: "medium",
    coat: "moderate",
    genetic_markers: ["PDP1"],
    common_health: ["intervertebral disc disease"],
  },
  Vizsla: {
    group: "Sporting",
    origin: "Hungary",
    size: "large",
    coat: "short",
    genetic_markers: ["HC", "PN"],
    common_health: ["hip dysplasia", "epilepsy"],
  },
  Weimaraner: {
    group: "Sporting",
    origin: "Germany",
    size: "large",
    coat: "short",
    genetic_markers: ["HOD", "SD2"],
    common_health: ["bloat", "hip dysplasia"],
  },
  "Welsh Springer Spaniel": {
    group: "Sporting",
    origin: "Wales",
    size: "medium",
    coat: "moderate",
    genetic_markers: ["FN", "GSE"],
    common_health: ["hip dysplasia", "glaucoma"],
  },
  "Wirehaired Pointing Griffon": {
    group: "Sporting",
    origin: "France",
    size: "medium",
    coat: "wire",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },

  // Hound Group
  "Afghan Hound": {
    group: "Hound",
    origin: "Afghanistan",
    size: "large",
    coat: "long",
    genetic_markers: ["CM", "DM"],
    common_health: ["cataracts", "hip dysplasia"],
  },
  "American English Coonhound": {
    group: "Hound",
    origin: "USA",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  "American Foxhound": {
    group: "Hound",
    origin: "USA",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["generally healthy"],
  },
  Basenji: {
    group: "Hound",
    origin: "Congo",
    size: "medium",
    coat: "short",
    genetic_markers: ["PRA", "FAN", "HNPK"],
    common_health: ["Fanconi syndrome", "HNPK", "PRA"],
  },
  "Basset Hound": {
    group: "Hound",
    origin: "France",
    size: "medium",
    coat: "short",
    genetic_markers: ["POAG", "TB"],
    common_health: ["hip dysplasia", "glaucoma", "bloat"],
  },
  Beagle: {
    group: "Hound",
    origin: "UK",
    size: "small",
    coat: "short",
    genetic_markers: ["NCCD", "IGS", "POAG", "MPS-VII"],
    common_health: ["epilepsy", "hypothyroidism", "obesity"],
  },
  "Black and Tan Coonhound": {
    group: "Hound",
    origin: "USA",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  Bloodhound: {
    group: "Hound",
    origin: "Belgium",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["bloat", "hip dysplasia"],
  },
  "Bluetick Coonhound": {
    group: "Hound",
    origin: "USA",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  Borzoi: {
    group: "Hound",
    origin: "Russia",
    size: "large",
    coat: "long",
    genetic_markers: ["DM"],
    common_health: ["bloat", "heart disease"],
  },
  Dachshund: {
    group: "Hound",
    origin: "Germany",
    size: "small",
    coat: "varies",
    genetic_markers: ["IVDD", "CD", "PRA-cord1", "NARDS", "LAMP2"],
    common_health: ["IVDD", "obesity", "dental disease"],
  },
  "English Foxhound": {
    group: "Hound",
    origin: "UK",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["generally healthy"],
  },
  Greyhound: {
    group: "Hound",
    origin: "UK",
    size: "large",
    coat: "short",
    genetic_markers: ["NCN", "DM"],
    common_health: ["bloat", "osteosarcoma"],
  },
  Harrier: {
    group: "Hound",
    origin: "UK",
    size: "medium",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  "Ibizan Hound": {
    group: "Hound",
    origin: "Spain",
    size: "large",
    coat: "short",
    genetic_markers: ["AD"],
    common_health: ["cataracts", "deafness"],
  },
  "Irish Wolfhound": {
    group: "Hound",
    origin: "Ireland",
    size: "giant",
    coat: "medium",
    genetic_markers: ["DM"],
    common_health: ["heart disease", "bloat", "cancer"],
  },
  "Norwegian Elkhound": {
    group: "Hound",
    origin: "Norway",
    size: "medium",
    coat: "dense",
    genetic_markers: ["PRA", "RD/OSD"],
    common_health: ["hip dysplasia", "PRA"],
  },
  Otterhound: {
    group: "Hound",
    origin: "UK",
    size: "large",
    coat: "dense",
    genetic_markers: ["EIC"],
    common_health: ["hip dysplasia", "bloat"],
  },
  "Petit Basset Griffon Vendéen": {
    group: "Hound",
    origin: "France",
    size: "small",
    coat: "rough",
    genetic_markers: ["POAG", "MH"],
    common_health: ["ear infections", "hip dysplasia"],
  },
  "Pharaoh Hound": {
    group: "Hound",
    origin: "Malta",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["generally healthy"],
  },
  Plott: {
    group: "Hound",
    origin: "USA",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["bloat"],
  },
  "Portuguese Podengo Pequeno": {
    group: "Hound",
    origin: "Portugal",
    size: "small",
    coat: "short/wire",
    genetic_markers: ["DM"],
    common_health: ["generally healthy"],
  },
  "Redbone Coonhound": {
    group: "Hound",
    origin: "USA",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  "Rhodesian Ridgeback": {
    group: "Hound",
    origin: "Zimbabwe",
    size: "large",
    coat: "short",
    genetic_markers: ["DM", "JME"],
    common_health: ["dermoid sinus", "hip dysplasia"],
  },
  Saluki: {
    group: "Hound",
    origin: "Middle East",
    size: "large",
    coat: "varies",
    genetic_markers: ["PRA", "DM"],
    common_health: ["heart disease"],
  },
  "Scottish Deerhound": {
    group: "Hound",
    origin: "Scotland",
    size: "giant",
    coat: "rough",
    genetic_markers: ["DM"],
    common_health: ["bloat", "heart disease"],
  },
  Sloughi: {
    group: "Hound",
    origin: "Morocco",
    size: "large",
    coat: "short",
    genetic_markers: ["PRA-rcd1a"],
    common_health: ["PRA"],
  },
  "Treeing Walker Coonhound": {
    group: "Hound",
    origin: "USA",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  Whippet: {
    group: "Hound",
    origin: "UK",
    size: "medium",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["generally healthy"],
  },

  // Working Group
  Akita: {
    group: "Working",
    origin: "Japan",
    size: "large",
    coat: "dense",
    genetic_markers: ["PRA", "VKH", "SA"],
    common_health: ["hip dysplasia", "bloat", "hypothyroidism"],
  },
  "Alaskan Malamute": {
    group: "Working",
    origin: "USA",
    size: "giant",
    coat: "dense",
    genetic_markers: ["CD", "DM", "POAG"],
    common_health: ["hip dysplasia", "CD"],
  },
  "Anatolian Shepherd Dog": {
    group: "Working",
    origin: "Turkey",
    size: "giant",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  "Bernese Mountain Dog": {
    group: "Working",
    origin: "Switzerland",
    size: "giant",
    coat: "long",
    genetic_markers: ["VWD", "DM", "PRA-prcd", "SOD1"],
    common_health: ["cancer", "bloat", "hip dysplasia"],
  },
  "Black Russian Terrier": {
    group: "Working",
    origin: "Russia",
    size: "giant",
    coat: "double",
    genetic_markers: ["HC", "DM"],
    common_health: ["hip dysplasia", "elbow dysplasia"],
  },
  Boerboel: {
    group: "Working",
    origin: "South Africa",
    size: "giant",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "elbow dysplasia"],
  },
  Boxer: {
    group: "Working",
    origin: "Germany",
    size: "large",
    coat: "short",
    genetic_markers: ["ARVC", "DM", "NCL-A"],
    common_health: ["cancer", "heart disease", "bloat"],
  },
  Bullmastiff: {
    group: "Working",
    origin: "UK",
    size: "giant",
    coat: "short",
    genetic_markers: ["DM", "CMR1"],
    common_health: ["hip dysplasia", "bloat", "cancer"],
  },
  "Cane Corso": {
    group: "Working",
    origin: "Italy",
    size: "giant",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "cherry eye"],
  },
  "Doberman Pinscher": {
    group: "Working",
    origin: "Germany",
    size: "large",
    coat: "short",
    genetic_markers: ["DCM1", "DCM2", "VWD", "DM", "NARD"],
    common_health: ["DCM", "VWD", "wobbler syndrome"],
  },
  "Dogue de Bordeaux": {
    group: "Working",
    origin: "France",
    size: "giant",
    coat: "short",
    genetic_markers: ["CMR1", "DM"],
    common_health: ["bloat", "hip dysplasia"],
  },
  "German Pinscher": {
    group: "Working",
    origin: "Germany",
    size: "medium",
    coat: "short",
    genetic_markers: ["VWD"],
    common_health: ["hip dysplasia", "VWD"],
  },
  "Giant Schnauzer": {
    group: "Working",
    origin: "Germany",
    size: "giant",
    coat: "wiry",
    genetic_markers: ["DM", "CMSD"],
    common_health: ["hip dysplasia", "bloat"],
  },
  "Great Dane": {
    group: "Working",
    origin: "Germany",
    size: "giant",
    coat: "short",
    genetic_markers: ["DM", "DCM"],
    common_health: ["bloat", "DCM", "hip dysplasia"],
  },
  "Great Pyrenees": {
    group: "Working",
    origin: "France",
    size: "giant",
    coat: "double",
    genetic_markers: ["GDNF", "DM", "MDR1"],
    common_health: ["hip dysplasia", "bloat"],
  },
  "Greater Swiss Mountain Dog": {
    group: "Working",
    origin: "Switzerland",
    size: "giant",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["bloat", "hip dysplasia"],
  },
  Komondor: {
    group: "Working",
    origin: "Hungary",
    size: "giant",
    coat: "corded",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "bloat"],
  },
  Kuvasz: {
    group: "Working",
    origin: "Hungary",
    size: "giant",
    coat: "dense",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  Leonberger: {
    group: "Working",
    origin: "Germany",
    size: "giant",
    coat: "long",
    genetic_markers: ["LEMP", "LPN1", "LPN2", "DM"],
    common_health: ["hip dysplasia", "bloat", "LEMP"],
  },
  Mastiff: {
    group: "Working",
    origin: "UK",
    size: "giant",
    coat: "short",
    genetic_markers: ["DM", "CMR1"],
    common_health: ["bloat", "hip dysplasia", "cancer"],
  },
  "Neapolitan Mastiff": {
    group: "Working",
    origin: "Italy",
    size: "giant",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "cherry eye"],
  },
  Newfoundland: {
    group: "Working",
    origin: "Canada",
    size: "giant",
    coat: "double",
    genetic_markers: ["DM", "SAS"],
    common_health: ["hip dysplasia", "SAS", "cystinuria"],
  },
  "Portuguese Water Dog": {
    group: "Working",
    origin: "Portugal",
    size: "medium",
    coat: "curly",
    genetic_markers: ["PRA-prcd", "JDCM", "GM1", "EOPRA"],
    common_health: ["hip dysplasia", "GM1", "JDCM"],
  },
  Rottweiler: {
    group: "Working",
    origin: "Germany",
    size: "large",
    coat: "short",
    genetic_markers: ["DM", "JME", "LCA", "VWD"],
    common_health: ["hip dysplasia", "cancer", "bloat"],
  },
  "Saint Bernard": {
    group: "Working",
    origin: "Switzerland",
    size: "giant",
    coat: "varies",
    genetic_markers: ["DM", "HUU"],
    common_health: ["hip dysplasia", "bloat", "entropion"],
  },
  Samoyed: {
    group: "Working",
    origin: "Siberia",
    size: "large",
    coat: "double",
    genetic_markers: ["PRA-XL", "RD/OSD", "DM"],
    common_health: ["hip dysplasia", "diabetes", "PRA"],
  },
  "Siberian Husky": {
    group: "Working",
    origin: "Siberia",
    size: "large",
    coat: "double",
    genetic_markers: ["DM", "PRA-XL", "CD"],
    common_health: ["hip dysplasia", "eye disease"],
  },
  "Standard Schnauzer": {
    group: "Working",
    origin: "Germany",
    size: "medium",
    coat: "wiry",
    genetic_markers: ["DM", "CMSD"],
    common_health: ["hip dysplasia"],
  },
  "Tibetan Mastiff": {
    group: "Working",
    origin: "Tibet",
    size: "giant",
    coat: "double",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "hypothyroidism"],
  },

  // Terrier Group
  "Airedale Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "large",
    coat: "wiry",
    genetic_markers: ["DM", "CP"],
    common_health: ["hip dysplasia", "hypothyroidism"],
  },
  "American Staffordshire Terrier": {
    group: "Terrier",
    origin: "USA",
    size: "medium",
    coat: "short",
    genetic_markers: ["NCL-A", "DM"],
    common_health: ["hip dysplasia", "heart disease"],
  },
  "Australian Terrier": {
    group: "Terrier",
    origin: "Australia",
    size: "small",
    coat: "rough",
    genetic_markers: ["DM"],
    common_health: ["diabetes", "patellar luxation"],
  },
  "Bedlington Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "medium",
    coat: "curly",
    genetic_markers: ["CT", "DM"],
    common_health: ["copper toxicosis", "PRA"],
  },
  "Border Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "wiry",
    genetic_markers: ["CECS", "SCA"],
    common_health: ["hip dysplasia", "CECS"],
  },
  "Bull Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "medium",
    coat: "short",
    genetic_markers: ["PLL", "LAD", "HS"],
    common_health: ["deafness", "heart disease", "kidney disease"],
  },
  "Cairn Terrier": {
    group: "Terrier",
    origin: "Scotland",
    size: "small",
    coat: "shaggy",
    genetic_markers: ["CMSD", "OC", "DM"],
    common_health: ["CMSD", "PLL"],
  },
  "Cesky Terrier": {
    group: "Terrier",
    origin: "Czech Republic",
    size: "small",
    coat: "silky",
    genetic_markers: ["DM"],
    common_health: ["Scotty cramp"],
  },
  "Dandie Dinmont Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "soft",
    genetic_markers: ["DM"],
    common_health: ["glaucoma", "epilepsy"],
  },
  "Fox Terrier (Smooth)": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "smooth",
    genetic_markers: ["DM", "PLL", "SCA"],
    common_health: ["deafness", "Legg-Perthes"],
  },
  "Fox Terrier (Wire)": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "wire",
    genetic_markers: ["DM"],
    common_health: ["deafness", "Legg-Perthes"],
  },
  "Glen of Imaal Terrier": {
    group: "Terrier",
    origin: "Ireland",
    size: "small",
    coat: "harsh",
    genetic_markers: ["CPRA3", "DM"],
    common_health: ["CPRA"],
  },
  "Irish Terrier": {
    group: "Terrier",
    origin: "Ireland",
    size: "medium",
    coat: "wiry",
    genetic_markers: ["DM", "HFH"],
    common_health: ["hyperkeratosis"],
  },
  "Kerry Blue Terrier": {
    group: "Terrier",
    origin: "Ireland",
    size: "medium",
    coat: "soft",
    genetic_markers: ["VWD", "CMSD", "DM"],
    common_health: ["hip dysplasia", "entropion"],
  },
  "Lakeland Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "wiry",
    genetic_markers: ["DM"],
    common_health: ["Legg-Perthes", "lens luxation"],
  },
  "Manchester Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "smooth",
    genetic_markers: ["VWD", "DM"],
    common_health: ["VWD", "Legg-Perthes"],
  },
  "Miniature Bull Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "short",
    genetic_markers: ["PLL", "LAD"],
    common_health: ["lens luxation", "kidney disease"],
  },
  "Miniature Schnauzer": {
    group: "Terrier",
    origin: "Germany",
    size: "small",
    coat: "wiry",
    genetic_markers: ["PRA-B", "MPS-IIIA", "DM", "CMSD"],
    common_health: ["diabetes", "pancreatitis", "bladder stones"],
  },
  "Norfolk Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "wiry",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  "Norwich Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "wiry",
    genetic_markers: ["UAS", "DM"],
    common_health: ["upper airway syndrome"],
  },
  "Parson Russell Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "rough",
    genetic_markers: ["PLL", "SCA", "LOA", "DM"],
    common_health: ["lens luxation", "deafness"],
  },
  "Russell Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "small",
    coat: "smooth/rough",
    genetic_markers: ["PLL", "SCA", "LOA", "DM"],
    common_health: ["lens luxation", "Legg-Perthes"],
  },
  "Scottish Terrier": {
    group: "Terrier",
    origin: "Scotland",
    size: "small",
    coat: "wiry",
    genetic_markers: ["VWD", "CMO", "DM"],
    common_health: ["bladder cancer", "VWD", "CMO"],
  },
  "Sealyham Terrier": {
    group: "Terrier",
    origin: "Wales",
    size: "small",
    coat: "wiry",
    genetic_markers: ["PLL"],
    common_health: ["lens luxation", "deafness"],
  },
  "Skye Terrier": {
    group: "Terrier",
    origin: "Scotland",
    size: "small",
    coat: "long",
    genetic_markers: ["DM"],
    common_health: ["intervertebral disc disease"],
  },
  "Soft Coated Wheaten Terrier": {
    group: "Terrier",
    origin: "Ireland",
    size: "medium",
    coat: "silky",
    genetic_markers: ["DM", "RD"],
    common_health: ["protein-losing nephropathy", "PLN"],
  },
  "Staffordshire Bull Terrier": {
    group: "Terrier",
    origin: "UK",
    size: "medium",
    coat: "smooth",
    genetic_markers: ["HC", "L-2-HGA", "DM"],
    common_health: ["L-2-HGA", "cataracts"],
  },
  "Welsh Terrier": {
    group: "Terrier",
    origin: "Wales",
    size: "small",
    coat: "wiry",
    genetic_markers: ["VWD", "DM", "PLL"],
    common_health: ["glaucoma", "hypothyroidism"],
  },
  "West Highland White Terrier": {
    group: "Terrier",
    origin: "Scotland",
    size: "small",
    coat: "harsh",
    genetic_markers: ["CMO", "GRMD", "CMSD", "PRA3", "DM"],
    common_health: ["CMO", "skin disease", "PLL"],
  },

  // Toy Group
  Affenpinscher: {
    group: "Toy",
    origin: "Germany",
    size: "toy",
    coat: "rough",
    genetic_markers: ["PRA", "DM"],
    common_health: ["patellar luxation", "hip dysplasia"],
  },
  "Brussels Griffon": {
    group: "Toy",
    origin: "Belgium",
    size: "toy",
    coat: "rough/smooth",
    genetic_markers: ["CM", "DM"],
    common_health: ["eye problems", "hip dysplasia"],
  },
  "Cavalier King Charles Spaniel": {
    group: "Toy",
    origin: "UK",
    size: "toy",
    coat: "silky",
    genetic_markers: ["EF", "DM", "MPS-I", "MVD"],
    common_health: ["MVD", "SM", "EF"],
  },
  Chihuahua: {
    group: "Toy",
    origin: "Mexico",
    size: "toy",
    coat: "smooth/long",
    genetic_markers: ["DM", "NCL-A", "PLL", "CMSD"],
    common_health: ["patellar luxation", "heart disease", "hydrocephalus"],
  },
  "Chinese Crested": {
    group: "Toy",
    origin: "China",
    size: "toy",
    coat: "hairless/powder puff",
    genetic_markers: ["PLL", "PRA-prcd", "DM"],
    common_health: ["dental disease", "PLL"],
  },
  "English Toy Spaniel": {
    group: "Toy",
    origin: "UK",
    size: "toy",
    coat: "silky",
    genetic_markers: ["PFK", "DM"],
    common_health: ["heart disease", "eye problems"],
  },
  Havanese: {
    group: "Toy",
    origin: "Cuba",
    size: "toy",
    coat: "silky",
    genetic_markers: ["PRA", "DM", "CMSD"],
    common_health: ["patellar luxation", "deafness"],
  },
  "Italian Greyhound": {
    group: "Toy",
    origin: "Italy",
    size: "toy",
    coat: "short",
    genetic_markers: ["PRA-IVRA", "DM"],
    common_health: ["dental disease", "fractures"],
  },
  "Japanese Chin": {
    group: "Toy",
    origin: "Japan",
    size: "toy",
    coat: "silky",
    genetic_markers: ["GM2", "DM"],
    common_health: ["heart murmurs", "eye problems"],
  },
  Maltese: {
    group: "Toy",
    origin: "Malta",
    size: "toy",
    coat: "silky",
    genetic_markers: ["NEwS", "DM", "IVDD"],
    common_health: ["dental disease", "patellar luxation"],
  },
  "Manchester Terrier (Toy)": {
    group: "Toy",
    origin: "UK",
    size: "toy",
    coat: "smooth",
    genetic_markers: ["VWD", "DM"],
    common_health: ["VWD", "Legg-Perthes"],
  },
  "Miniature Pinscher": {
    group: "Toy",
    origin: "Germany",
    size: "toy",
    coat: "smooth",
    genetic_markers: ["PRA6", "MPS-VI", "DM"],
    common_health: ["patellar luxation", "Legg-Perthes"],
  },
  Papillon: {
    group: "Toy",
    origin: "France",
    size: "toy",
    coat: "silky",
    genetic_markers: ["PRA-prcd", "VWD", "DM"],
    common_health: ["patellar luxation", "PRA"],
  },
  Pekingese: {
    group: "Toy",
    origin: "China",
    size: "toy",
    coat: "long",
    genetic_markers: ["IVDD", "DM"],
    common_health: ["IVDD", "eye problems"],
  },
  Pomeranian: {
    group: "Toy",
    origin: "Germany",
    size: "toy",
    coat: "double",
    genetic_markers: ["PLL", "GME", "DM", "IVDD"],
    common_health: ["patellar luxation", "tracheal collapse"],
  },
  Pug: {
    group: "Toy",
    origin: "China",
    size: "toy",
    coat: "short",
    genetic_markers: ["PDE", "DM", "NCL-A"],
    common_health: ["BOAS", "PDE", "eye problems"],
  },
  "Shih Tzu": {
    group: "Toy",
    origin: "China",
    size: "toy",
    coat: "long",
    genetic_markers: ["PRA-prcd", "RD", "DM", "IVDD"],
    common_health: ["BOAS", "eye disease", "IVDD"],
  },
  "Silky Terrier": {
    group: "Toy",
    origin: "Australia",
    size: "toy",
    coat: "silky",
    genetic_markers: ["DM"],
    common_health: ["patellar luxation", "Legg-Perthes"],
  },
  "Toy Fox Terrier": {
    group: "Toy",
    origin: "USA",
    size: "toy",
    coat: "short",
    genetic_markers: ["PLL", "VWD", "DM"],
    common_health: ["patellar luxation", "Legg-Perthes"],
  },
  "Yorkshire Terrier": {
    group: "Toy",
    origin: "UK",
    size: "toy",
    coat: "silky",
    genetic_markers: ["PLL", "DM", "IVDD", "PAM"],
    common_health: ["dental disease", "tracheal collapse", "patellar luxation"],
  },

  // Non-Sporting Group
  "American Eskimo Dog": {
    group: "Non-Sporting",
    origin: "USA",
    size: "medium",
    coat: "double",
    genetic_markers: ["PRA-prcd", "DM"],
    common_health: ["hip dysplasia", "PRA"],
  },
  "Bichon Frise": {
    group: "Non-Sporting",
    origin: "France",
    size: "small",
    coat: "curly",
    genetic_markers: ["PRA-prcd", "CMSD", "DM"],
    common_health: ["allergies", "bladder stones"],
  },
  "Boston Terrier": {
    group: "Non-Sporting",
    origin: "USA",
    size: "small",
    coat: "smooth",
    genetic_markers: ["HC", "DM", "CMR1"],
    common_health: ["BOAS", "eye problems", "HC"],
  },
  Bulldog: {
    group: "Non-Sporting",
    origin: "UK",
    size: "medium",
    coat: "short",
    genetic_markers: ["HUU", "CMR1", "DM", "IVDD"],
    common_health: ["BOAS", "hip dysplasia", "skin problems"],
  },
  "Chinese Shar-Pei": {
    group: "Non-Sporting",
    origin: "China",
    size: "medium",
    coat: "harsh",
    genetic_markers: ["SPAID", "DM"],
    common_health: ["skin problems", "entropion", "SPAID"],
  },
  "Chow Chow": {
    group: "Non-Sporting",
    origin: "China",
    size: "medium",
    coat: "dense",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "entropion"],
  },
  "Coton de Tulear": {
    group: "Non-Sporting",
    origin: "Madagascar",
    size: "small",
    coat: "cotton",
    genetic_markers: ["CMD", "VWD", "PRA-prcd", "DM"],
    common_health: ["luxating patella", "hip dysplasia"],
  },
  Dalmatian: {
    group: "Non-Sporting",
    origin: "Croatia",
    size: "large",
    coat: "short",
    genetic_markers: ["HUU", "DM"],
    common_health: ["HUU", "deafness"],
  },
  "Finnish Spitz": {
    group: "Non-Sporting",
    origin: "Finland",
    size: "medium",
    coat: "dense",
    genetic_markers: ["PRA", "DM"],
    common_health: ["hip dysplasia", "epilepsy"],
  },
  "French Bulldog": {
    group: "Non-Sporting",
    origin: "France",
    size: "small",
    coat: "smooth",
    genetic_markers: ["CMR1", "DM", "JHC", "IVDD", "HUU"],
    common_health: ["BOAS", "IVDD", "allergies"],
  },
  Keeshond: {
    group: "Non-Sporting",
    origin: "Netherlands",
    size: "medium",
    coat: "double",
    genetic_markers: ["PRA-prcd", "POAG", "DM"],
    common_health: ["hip dysplasia", "heart disease"],
  },
  "Lhasa Apso": {
    group: "Non-Sporting",
    origin: "Tibet",
    size: "small",
    coat: "long",
    genetic_markers: ["PRA-prcd", "RD", "DM", "IVDD"],
    common_health: ["eye problems", "kidney disease"],
  },
  Lowchen: {
    group: "Non-Sporting",
    origin: "France",
    size: "small",
    coat: "long",
    genetic_markers: ["PRA", "DM"],
    common_health: ["patellar luxation", "PRA"],
  },
  "Norwegian Lundehund": {
    group: "Non-Sporting",
    origin: "Norway",
    size: "small",
    coat: "dense",
    genetic_markers: ["IL", "DM"],
    common_health: ["intestinal lymphangiectasia"],
  },
  "Poodle (Miniature)": {
    group: "Non-Sporting",
    origin: "France",
    size: "small",
    coat: "curly",
    genetic_markers: ["PRA-prcd", "VWD", "DM", "NEwS"],
    common_health: ["PRA", "epilepsy", "Addison's"],
  },
  "Poodle (Standard)": {
    group: "Non-Sporting",
    origin: "France",
    size: "large",
    coat: "curly",
    genetic_markers: ["PRA-prcd", "VWD", "DM", "NEwS"],
    common_health: ["bloat", "Addison's", "hip dysplasia"],
  },
  "Poodle (Toy)": {
    group: "Non-Sporting",
    origin: "France",
    size: "toy",
    coat: "curly",
    genetic_markers: ["PRA-prcd", "VWD", "DM", "NEwS"],
    common_health: ["PRA", "patellar luxation"],
  },
  Schipperke: {
    group: "Non-Sporting",
    origin: "Belgium",
    size: "small",
    coat: "double",
    genetic_markers: ["MPS-IIIB", "DM"],
    common_health: ["MPS-IIIB", "hypothyroidism"],
  },
  "Shiba Inu": {
    group: "Non-Sporting",
    origin: "Japan",
    size: "small",
    coat: "double",
    genetic_markers: ["GM1", "DM"],
    common_health: ["allergies", "patellar luxation"],
  },
  "Tibetan Spaniel": {
    group: "Non-Sporting",
    origin: "Tibet",
    size: "small",
    coat: "double",
    genetic_markers: ["PRA-prcd", "DM"],
    common_health: ["PRA", "patellar luxation"],
  },
  "Tibetan Terrier": {
    group: "Non-Sporting",
    origin: "Tibet",
    size: "medium",
    coat: "double",
    genetic_markers: ["PLL", "NCL-A", "DM"],
    common_health: ["PLL", "hip dysplasia"],
  },
  Xoloitzcuintli: {
    group: "Non-Sporting",
    origin: "Mexico",
    size: "medium",
    coat: "hairless/coated",
    genetic_markers: ["FOXI3"],
    common_health: ["dental issues", "skin problems"],
  },

  // Herding Group
  "Australian Cattle Dog": {
    group: "Herding",
    origin: "Australia",
    size: "medium",
    coat: "short",
    genetic_markers: ["PRA-prcd", "DM", "NCL-A"],
    common_health: ["hip dysplasia", "deafness", "PRA"],
  },
  "Australian Shepherd": {
    group: "Herding",
    origin: "USA",
    size: "medium",
    coat: "medium",
    genetic_markers: ["MDR1", "CEA", "HSF4", "PRA-prcd", "CD", "DM", "HC"],
    common_health: ["hip dysplasia", "CEA", "MDR1", "epilepsy"],
  },
  "Bearded Collie": {
    group: "Herding",
    origin: "Scotland",
    size: "medium",
    coat: "long",
    genetic_markers: ["CEA", "DM"],
    common_health: ["hip dysplasia", "Addison's"],
  },
  Beauceron: {
    group: "Herding",
    origin: "France",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "bloat"],
  },
  "Belgian Malinois": {
    group: "Herding",
    origin: "Belgium",
    size: "large",
    coat: "short",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "elbow dysplasia"],
  },
  "Belgian Sheepdog": {
    group: "Herding",
    origin: "Belgium",
    size: "large",
    coat: "long",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "epilepsy"],
  },
  "Belgian Tervuren": {
    group: "Herding",
    origin: "Belgium",
    size: "large",
    coat: "long",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "epilepsy"],
  },
  "Border Collie": {
    group: "Herding",
    origin: "UK",
    size: "medium",
    coat: "medium",
    genetic_markers: ["CEA", "NCL", "TNS", "MDR1", "IGS", "DM"],
    common_health: ["hip dysplasia", "CEA", "epilepsy"],
  },
  "Bouvier des Flandres": {
    group: "Herding",
    origin: "Belgium",
    size: "large",
    coat: "rough",
    genetic_markers: ["DM", "LPN2"],
    common_health: ["hip dysplasia", "bloat"],
  },
  Briard: {
    group: "Herding",
    origin: "France",
    size: "large",
    coat: "long",
    genetic_markers: ["CSNB", "DM"],
    common_health: ["hip dysplasia", "CSNB"],
  },
  "Canaan Dog": {
    group: "Herding",
    origin: "Israel",
    size: "medium",
    coat: "double",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia", "hypothyroidism"],
  },
  "Cardigan Welsh Corgi": {
    group: "Herding",
    origin: "Wales",
    size: "small",
    coat: "medium",
    genetic_markers: ["PRA-rcd3", "DM", "VWD"],
    common_health: ["IVDD", "hip dysplasia", "PRA"],
  },
  "Collie (Rough)": {
    group: "Herding",
    origin: "Scotland",
    size: "large",
    coat: "long",
    genetic_markers: ["CEA", "MDR1", "DM", "DMS", "IGS"],
    common_health: ["CEA", "MDR1", "bloat"],
  },
  "Collie (Smooth)": {
    group: "Herding",
    origin: "Scotland",
    size: "large",
    coat: "short",
    genetic_markers: ["CEA", "MDR1", "DM", "DMS"],
    common_health: ["CEA", "MDR1", "bloat"],
  },
  "Entlebucher Mountain Dog": {
    group: "Herding",
    origin: "Switzerland",
    size: "medium",
    coat: "short",
    genetic_markers: ["PRA-prcd", "DM"],
    common_health: ["hip dysplasia", "PRA"],
  },
  "Finnish Lapphund": {
    group: "Herding",
    origin: "Finland",
    size: "medium",
    coat: "double",
    genetic_markers: ["PRA-prcd", "DM"],
    common_health: ["hip dysplasia", "PRA"],
  },
  "German Shepherd Dog": {
    group: "Herding",
    origin: "Germany",
    size: "large",
    coat: "double",
    genetic_markers: ["DM", "MDR1", "EOAD", "DCM"],
    common_health: ["hip dysplasia", "elbow dysplasia", "DM", "bloat"],
  },
  "Icelandic Sheepdog": {
    group: "Herding",
    origin: "Iceland",
    size: "medium",
    coat: "double",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  "Miniature American Shepherd": {
    group: "Herding",
    origin: "USA",
    size: "small",
    coat: "medium",
    genetic_markers: ["MDR1", "CEA", "PRA-prcd", "CD", "DM", "HC"],
    common_health: ["hip dysplasia", "CEA", "MDR1"],
  },
  "Norwegian Buhund": {
    group: "Herding",
    origin: "Norway",
    size: "medium",
    coat: "dense",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  "Old English Sheepdog": {
    group: "Herding",
    origin: "UK",
    size: "large",
    coat: "shaggy",
    genetic_markers: ["PCD", "MDR1", "DM"],
    common_health: ["hip dysplasia", "PCD", "deafness"],
  },
  "Pembroke Welsh Corgi": {
    group: "Herding",
    origin: "Wales",
    size: "small",
    coat: "medium",
    genetic_markers: ["DM", "VWD", "EIC"],
    common_health: ["IVDD", "hip dysplasia", "DM"],
  },
  "Polish Lowland Sheepdog": {
    group: "Herding",
    origin: "Poland",
    size: "medium",
    coat: "shaggy",
    genetic_markers: ["DM"],
    common_health: ["hip dysplasia"],
  },
  Puli: {
    group: "Herding",
    origin: "Hungary",
    size: "medium",
    coat: "corded",
    genetic_markers: ["DM", "PRA-prcd"],
    common_health: ["hip dysplasia", "PRA"],
  },
  "Pyrenean Shepherd": {
    group: "Herding",
    origin: "France",
    size: "medium",
    coat: "rough/smooth",
    genetic_markers: ["MDR1", "PRA", "CEA"],
    common_health: ["hip dysplasia", "epilepsy"],
  },
  "Shetland Sheepdog": {
    group: "Herding",
    origin: "Scotland",
    size: "small",
    coat: "double",
    genetic_markers: ["CEA", "MDR1", "VWD", "DM", "PRA"],
    common_health: ["CEA", "MDR1", "hip dysplasia"],
  },
  "Spanish Water Dog": {
    group: "Herding",
    origin: "Spain",
    size: "medium",
    coat: "curly",
    genetic_markers: ["PRA-prcd", "DM"],
    common_health: ["hip dysplasia", "PRA"],
  },
  "Swedish Vallhund": {
    group: "Herding",
    origin: "Sweden",
    size: "small",
    coat: "medium",
    genetic_markers: ["PRA", "DM"],
    common_health: ["hip dysplasia", "PRA"],
  },

  // Designer/Mixed Breeds (Common)
  Labradoodle: {
    group: "Mixed",
    origin: "Australia",
    size: "large",
    coat: "curly/wavy",
    genetic_markers: ["EIC", "PRA-prcd", "VWD", "DM"],
    common_health: ["hip dysplasia", "PRA", "Addison's"],
  },
  Goldendoodle: {
    group: "Mixed",
    origin: "USA",
    size: "large",
    coat: "curly/wavy",
    genetic_markers: ["PRA1", "PRA2", "ICT-A", "VWD"],
    common_health: ["hip dysplasia", "allergies", "bloat"],
  },
  Cockapoo: {
    group: "Mixed",
    origin: "USA",
    size: "small",
    coat: "curly",
    genetic_markers: ["PRA-prcd", "FN", "VWD"],
    common_health: ["ear infections", "allergies"],
  },
  Puggle: {
    group: "Mixed",
    origin: "USA",
    size: "small",
    coat: "short",
    genetic_markers: ["PDE", "NCCD"],
    common_health: ["BOAS", "obesity", "epilepsy"],
  },
  Maltipoo: {
    group: "Mixed",
    origin: "USA",
    size: "toy",
    coat: "curly",
    genetic_markers: ["PRA-prcd", "NEwS", "VWD"],
    common_health: ["patellar luxation", "dental disease"],
  },
  Yorkipoo: {
    group: "Mixed",
    origin: "USA",
    size: "toy",
    coat: "curly/silky",
    genetic_markers: ["PLL", "PRA-prcd", "VWD"],
    common_health: ["patellar luxation", "tracheal collapse"],
  },
  Cavapoo: {
    group: "Mixed",
    origin: "Australia",
    size: "small",
    coat: "curly/wavy",
    genetic_markers: ["EF", "PRA-prcd", "VWD"],
    common_health: ["heart disease", "hip dysplasia"],
  },
  Aussiedoodle: {
    group: "Mixed",
    origin: "USA",
    size: "medium",
    coat: "curly/wavy",
    genetic_markers: ["MDR1", "CEA", "PRA-prcd", "VWD"],
    common_health: ["hip dysplasia", "epilepsy"],
  },
  Bernedoodle: {
    group: "Mixed",
    origin: "Canada",
    size: "large",
    coat: "curly/wavy",
    genetic_markers: ["VWD", "DM", "PRA-prcd"],
    common_health: ["hip dysplasia", "bloat"],
  },
  Sheepadoodle: {
    group: "Mixed",
    origin: "USA",
    size: "large",
    coat: "curly",
    genetic_markers: ["PCD", "PRA-prcd", "VWD"],
    common_health: ["hip dysplasia", "bloat"],
  },
  Pomsky: {
    group: "Mixed",
    origin: "USA",
    size: "small",
    coat: "double",
    genetic_markers: ["PLL", "DM", "PRA-XL"],
    common_health: ["dental disease", "allergies"],
  },
};

// COMPLETE CAT BREED DATABASE (70+ breeds)
export const CAT_BREEDS = {
  Abyssinian: {
    group: "Shorthair",
    origin: "Ethiopia",
    coat: "ticked",
    genetic_markers: ["PRA-rdAc", "PK-Def", "ALPS", "MYHBP3"],
    common_health: ["PKD", "PRA", "dental disease"],
  },
  "American Bobtail": {
    group: "Shorthair",
    origin: "USA",
    coat: "semi-long",
    genetic_markers: ["HCM"],
    common_health: ["hip dysplasia"],
  },
  "American Curl": {
    group: "Longhair",
    origin: "USA",
    coat: "varies",
    genetic_markers: ["HCM", "PKD"],
    common_health: ["ear infections"],
  },
  "American Shorthair": {
    group: "Shorthair",
    origin: "USA",
    coat: "short",
    genetic_markers: ["HCM", "PKD"],
    common_health: ["HCM", "obesity"],
  },
  "American Wirehair": {
    group: "Shorthair",
    origin: "USA",
    coat: "wire",
    genetic_markers: ["HCM"],
    common_health: ["HCM"],
  },
  Balinese: {
    group: "Longhair",
    origin: "USA",
    coat: "long",
    genetic_markers: ["PRA", "GM1", "HCM"],
    common_health: ["PRA", "strabismus"],
  },
  Bengal: {
    group: "Shorthair",
    origin: "USA",
    coat: "spotted/marbled",
    genetic_markers: ["PRA-b", "PK-Def", "HCM", "PRA-rdAc"],
    common_health: ["HCM", "PRA", "FIP"],
  },
  Birman: {
    group: "Longhair",
    origin: "Burma",
    coat: "long",
    genetic_markers: ["HCM", "MPS-VI", "PKD"],
    common_health: ["HCM", "kidney disease"],
  },
  Bombay: {
    group: "Shorthair",
    origin: "USA",
    coat: "short",
    genetic_markers: ["HCM", "BCS"],
    common_health: ["HCM", "respiratory issues"],
  },
  "British Shorthair": {
    group: "Shorthair",
    origin: "UK",
    coat: "short",
    genetic_markers: ["HCM", "PKD", "ALPS"],
    common_health: ["HCM", "PKD", "obesity"],
  },
  "British Longhair": {
    group: "Longhair",
    origin: "UK",
    coat: "long",
    genetic_markers: ["HCM", "PKD"],
    common_health: ["HCM", "PKD"],
  },
  Burmese: {
    group: "Shorthair",
    origin: "Burma",
    coat: "short",
    genetic_markers: ["BCS", "HYP-BUR", "GM2", "HCM"],
    common_health: ["diabetes", "HCM"],
  },
  Burmilla: {
    group: "Shorthair",
    origin: "UK",
    coat: "short",
    genetic_markers: ["PKD", "HCM"],
    common_health: ["PKD", "kidney disease"],
  },
  Chartreux: {
    group: "Shorthair",
    origin: "France",
    coat: "short",
    genetic_markers: ["HCM", "PKD"],
    common_health: ["patellar luxation"],
  },
  Chausie: {
    group: "Shorthair",
    origin: "USA",
    coat: "short",
    genetic_markers: ["HCM"],
    common_health: ["IBD"],
  },
  "Cornish Rex": {
    group: "Shorthair",
    origin: "UK",
    coat: "rex",
    genetic_markers: ["HCM", "SMA"],
    common_health: ["HCM", "umbilical hernia"],
  },
  "Devon Rex": {
    group: "Shorthair",
    origin: "UK",
    coat: "rex",
    genetic_markers: ["HCM", "SMA", "CMS", "MYHBP3"],
    common_health: ["HCM", "patellar luxation"],
  },
  Donskoy: {
    group: "Hairless",
    origin: "Russia",
    coat: "hairless",
    genetic_markers: ["HCM"],
    common_health: ["skin sensitivity"],
  },
  "Egyptian Mau": {
    group: "Shorthair",
    origin: "Egypt",
    coat: "spotted",
    genetic_markers: ["PRA-CEP290", "PK-Def", "HCM"],
    common_health: ["allergies", "HCM"],
  },
  "Exotic Shorthair": {
    group: "Shorthair",
    origin: "USA",
    coat: "plush",
    genetic_markers: ["PKD", "HCM", "PRA-pd"],
    common_health: ["PKD", "BOAS", "dental disease"],
  },
  "Havana Brown": {
    group: "Shorthair",
    origin: "UK",
    coat: "short",
    genetic_markers: ["HCM"],
    common_health: ["respiratory infections"],
  },
  Himalayan: {
    group: "Longhair",
    origin: "USA",
    coat: "long",
    genetic_markers: ["PKD", "PRA-pd", "HCM"],
    common_health: ["PKD", "BOAS", "dental disease"],
  },
  "Japanese Bobtail": {
    group: "Shorthair",
    origin: "Japan",
    coat: "short/long",
    genetic_markers: ["HCM"],
    common_health: ["generally healthy"],
  },
  Javanese: {
    group: "Longhair",
    origin: "USA",
    coat: "long",
    genetic_markers: ["PRA", "HCM"],
    common_health: ["dental disease"],
  },
  "Khao Manee": {
    group: "Shorthair",
    origin: "Thailand",
    coat: "short",
    genetic_markers: ["HCM"],
    common_health: ["deafness (white cats)"],
  },
  Korat: {
    group: "Shorthair",
    origin: "Thailand",
    coat: "short",
    genetic_markers: ["GM1", "GM2", "HCM"],
    common_health: ["GM1", "GM2"],
  },
  LaPerm: {
    group: "Longhair",
    origin: "USA",
    coat: "curly",
    genetic_markers: ["HCM", "PKD"],
    common_health: ["generally healthy"],
  },
  Lykoi: {
    group: "Shorthair",
    origin: "USA",
    coat: "roan",
    genetic_markers: ["HCM"],
    common_health: ["generally healthy"],
  },
  "Maine Coon": {
    group: "Longhair",
    origin: "USA",
    coat: "long",
    genetic_markers: ["HCM", "SMA", "PKD", "PK-Def"],
    common_health: ["HCM", "SMA", "hip dysplasia"],
  },
  Manx: {
    group: "Shorthair",
    origin: "Isle of Man",
    coat: "short/long",
    genetic_markers: ["Manx", "HCM"],
    common_health: ["Manx syndrome", "arthritis"],
  },
  Munchkin: {
    group: "Shorthair",
    origin: "USA",
    coat: "varies",
    genetic_markers: ["HCM", "MLVD"],
    common_health: ["lordosis", "pectus excavatum"],
  },
  Nebelung: {
    group: "Longhair",
    origin: "Russia",
    coat: "long",
    genetic_markers: ["HCM"],
    common_health: ["obesity"],
  },
  "Norwegian Forest Cat": {
    group: "Longhair",
    origin: "Norway",
    coat: "long",
    genetic_markers: ["HCM", "PKD", "GSD-IV"],
    common_health: ["HCM", "GSD-IV", "hip dysplasia"],
  },
  Ocicat: {
    group: "Shorthair",
    origin: "USA",
    coat: "spotted",
    genetic_markers: ["PRA-rdAc", "PK-Def", "HCM"],
    common_health: ["periodontal disease"],
  },
  "Oriental Shorthair": {
    group: "Shorthair",
    origin: "USA",
    coat: "short",
    genetic_markers: ["PRA", "GM1", "HCM"],
    common_health: ["dental disease", "HCM"],
  },
  "Oriental Longhair": {
    group: "Longhair",
    origin: "USA",
    coat: "long",
    genetic_markers: ["PRA", "GM1", "HCM"],
    common_health: ["dental disease", "HCM"],
  },
  Persian: {
    group: "Longhair",
    origin: "Iran",
    coat: "long",
    genetic_markers: ["PKD", "PRA-pd", "HCM", "ALPS"],
    common_health: ["PKD", "BOAS", "dental disease", "eye issues"],
  },
  Peterbald: {
    group: "Hairless",
    origin: "Russia",
    coat: "hairless/brush",
    genetic_markers: ["HCM"],
    common_health: ["skin sensitivity"],
  },
  Pixiebob: {
    group: "Shorthair",
    origin: "USA",
    coat: "short/long",
    genetic_markers: ["HCM"],
    common_health: ["generally healthy"],
  },
  Ragamuffin: {
    group: "Longhair",
    origin: "USA",
    coat: "long",
    genetic_markers: ["HCM", "PKD"],
    common_health: ["obesity"],
  },
  Ragdoll: {
    group: "Longhair",
    origin: "USA",
    coat: "long",
    genetic_markers: ["HCM", "PKD", "MYHBP3"],
    common_health: ["HCM", "PKD"],
  },
  "Russian Blue": {
    group: "Shorthair",
    origin: "Russia",
    coat: "short",
    genetic_markers: ["HCM", "PKD"],
    common_health: ["generally healthy"],
  },
  Savannah: {
    group: "Shorthair",
    origin: "USA",
    coat: "spotted",
    genetic_markers: ["PRA-rdAc", "HCM"],
    common_health: ["HCM"],
  },
  "Scottish Fold": {
    group: "Shorthair",
    origin: "Scotland",
    coat: "short/long",
    genetic_markers: ["OCD", "HCM", "PKD"],
    common_health: ["OCD", "arthritis"],
  },
  "Selkirk Rex": {
    group: "Longhair",
    origin: "USA",
    coat: "curly",
    genetic_markers: ["PKD", "HCM"],
    common_health: ["PKD", "HCM"],
  },
  Siamese: {
    group: "Shorthair",
    origin: "Thailand",
    coat: "short",
    genetic_markers: ["PRA", "GM1", "HCM", "MYHBP3"],
    common_health: ["dental disease", "respiratory issues", "HCM"],
  },
  Siberian: {
    group: "Longhair",
    origin: "Russia",
    coat: "long",
    genetic_markers: ["HCM", "PKD"],
    common_health: ["generally healthy"],
  },
  Singapura: {
    group: "Shorthair",
    origin: "Singapore",
    coat: "short",
    genetic_markers: ["PRA-rdAc", "PK-Def", "HCM"],
    common_health: ["uterine inertia"],
  },
  Snowshoe: {
    group: "Shorthair",
    origin: "USA",
    coat: "short",
    genetic_markers: ["HCM"],
    common_health: ["generally healthy"],
  },
  Somali: {
    group: "Longhair",
    origin: "Somalia",
    coat: "long",
    genetic_markers: ["PRA-rdAc", "PK-Def", "HCM"],
    common_health: ["PRA", "dental disease"],
  },
  Sphynx: {
    group: "Hairless",
    origin: "Canada",
    coat: "hairless",
    genetic_markers: ["HCM", "SMA", "MYHBP3"],
    common_health: ["HCM", "skin conditions"],
  },
  Tonkinese: {
    group: "Shorthair",
    origin: "Canada",
    coat: "short",
    genetic_markers: ["PRA", "GM1", "HCM", "BCS"],
    common_health: ["gingivitis"],
  },
  Toyger: {
    group: "Shorthair",
    origin: "USA",
    coat: "short",
    genetic_markers: ["HCM"],
    common_health: ["generally healthy"],
  },
  "Turkish Angora": {
    group: "Longhair",
    origin: "Turkey",
    coat: "long",
    genetic_markers: ["HCM", "Ataxia"],
    common_health: ["deafness (white cats)", "ataxia"],
  },
  "Turkish Van": {
    group: "Longhair",
    origin: "Turkey",
    coat: "semi-long",
    genetic_markers: ["HCM"],
    common_health: ["generally healthy"],
  },
  "York Chocolate": {
    group: "Longhair",
    origin: "USA",
    coat: "long",
    genetic_markers: ["HCM"],
    common_health: ["generally healthy"],
  },

  // Domestic Mixed
  "Domestic Shorthair": {
    group: "Mixed",
    origin: "Various",
    coat: "short",
    genetic_markers: ["HCM", "PKD", "PRA"],
    common_health: ["obesity", "dental disease"],
  },
  "Domestic Longhair": {
    group: "Mixed",
    origin: "Various",
    coat: "long",
    genetic_markers: ["HCM", "PKD", "PRA"],
    common_health: ["obesity", "dental disease", "hairballs"],
  },
  "Domestic Medium Hair": {
    group: "Mixed",
    origin: "Various",
    coat: "medium",
    genetic_markers: ["HCM", "PKD", "PRA"],
    common_health: ["obesity", "dental disease"],
  },
};

// GET
